### ISSUE TITLE
Issue with WMI_exporter

### ISSUE THREAD

**Issue by veeraprathap12** [martinlindhe/wmi_exporter#441] opened 2019-11-24 17:26 UTC
we need to enable collectors. For enabling we are using the following command execution but we unable to see the metrics
msiexec /i wmi_exporter-0.9.0-amd64.msi ENABLED_COLLECTORS=os,tcp LISTEN_PORT=9182
Is this right process to enable collectors
 please help me out of this issue we have gone through your document
but we still facing issue

**Comment by breed808** [comment] 2019-11-25 00:15
Hi @veeraprathap12, you can omit the `LISTEN_PORT` as the default port is `9182/tcp`.

What issues are you experiencing when attempting to view the metrics? For reference, I'm using the following command to install the exporter: `msiexec /i "wmi_exporter-0.9.0-amd64.msi" 'ENABLED_COLLECTORS=os,tcp'`

**Comment by veeraprathap12** [comment] 2019-11-25 00:19
when  we are using the following command it executing command with out error but we unable to see the metrics when we run localhost:9182

msiexec /i wmi_exporter-0.9.0-amd64.msi ENABLED_COLLECTORS=os,tcp

**Comment by breed808** [comment] 2019-11-25 00:23
When installed with the MSI, the exporter will run as a system service (`wmi_exporter`). You can view the service status using `services.msc` or by running `Get-Service wmi_exporter` with Powershell.

Assuming the service is running correctly, what sort of output do you receive when accessing http://localhost:9182/metrics in a browser on the local machine?

**Comment by veeraprathap12** [comment] 2019-11-25 00:30
yes, we saw in windows services wmi_exporter it was in running state after executing the command when  we looked again it displays only the default metrics not displaying enabled metrics

**Comment by breed808** [comment] 2019-11-25 00:34
OK, so there's no metrics from the `os` and `tcp` exporters? Are there any errors in the `Application` Windows event log from the exporter?

**Comment by veeraprathap12** [comment] 2019-11-25 00:41
![3metr](https://user-images.githubusercontent.com/57307102/69504600-f9d6e380-0ee9-11ea-9dae-d57fd387bc6a.PNG)
![2te](https://user-images.githubusercontent.com/57307102/69504601-fd6a6a80-0ee9-11ea-9460-2a6a35c4c36d.PNG)
![tes](https://user-images.githubusercontent.com/57307102/69504605-03f8e200-0eea-11ea-8780-cacf6f907413.PNG)

**Comment by veeraprathap12** [comment] 2019-11-25 00:41
no we didn't find any errors

**Comment by breed808** [comment] 2019-11-25 00:51
That's strange, looks like you have at least the `service` and `textfile` collectors running.
Can you re-install the MSI and try again? Alternatively, you can download the EXE and run it with the following `.\wmi_exporter-0.9.0-amd64.exe --telemetry.addr=":9183" --collectors.enabled="os,tcp"` and navigate to `http://localhost:9183/metrics` to test.

**Comment by veeraprathap12** [comment] 2019-11-25 01:18
By using .exe it was running we can see metrics but once we close cmd it stops running right
even it public IP acting as private IP here. For converting public IP we are using ngrok  software to convert public IP

**Comment by breed808** [comment] 2019-11-25 01:25
The metrics no longer being available when closing the EXE is expected. The EXE process is temporary, while the system service registered by the MSI will persist.

I don't believe public/private IPs are relevant to the issue; the exporter will bind to all available interfaces by default. Did re-installing the MSI resolve the issue?

**Comment by veeraprathap12** [comment] 2019-11-25 01:33
![new3](https://user-images.githubusercontent.com/57307102/69505783-440f9300-0ef1-11ea-8aac-d86d9fd7f3d8.PNG)
 we reinstall >msi still we are facing an issue. when we tried with .exe perfectly  we can get metrics 
![new](https://user-images.githubusercontent.com/57307102/69505777-3eb24880-0ef1-11ea-8063-ce82a09f4bac.PNG)

**Comment by veeraprathap12** [comment] 2019-11-25 01:34
but we are facing a problem msi file

**Comment by breed808** [comment] 2019-11-25 01:38
Your recent screenshot shows the `tcp` and `os`, is this from the MSI or EXE?
Rather than re-installing, perhaps uninstall the MSI first and then manually install once removal has been confirmed.

**Comment by veeraprathap12** [comment] 2019-11-25 01:44
The recent screenshot is with EXE
yes, we confirmed after reinstalling in services and uninstall programs

**Comment by breed808** [comment] 2019-11-25 01:57
What output are you receiving from the MSI service? Is it still the default collectors?

**Comment by veeraprathap12** [comment] 2019-11-25 02:00
yes, it still posting default collectors

**Comment by breed808** [comment] 2019-11-25 02:20
Can you open `services.msc` and copy and paste the "_Path to executable_" output?

You should have something like the following:
```
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled cpu,cs,memory,net,logical_disk,os,system --telemetry.addr :9182
```

**Comment by veeraprathap12** [comment] 2019-11-25 02:29
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter  --telemetry.addr :9182

**Comment by breed808** [comment] 2019-11-25 03:14
Looks like the `ENABLED_COLLECTORS` portion of your install command is being ignored or is incorrect. Do you have it surrounded by quotes when installing the MSI?
You could try to create an installation log: https://www.advancedinstaller.com/user-guide/qa-log.html

**Comment by veeraprathap12** [comment] 2019-11-25 03:22
how to enable  ENABLED_COLLLECTORS? can you help me with that?

**Comment by breed808** [comment] 2019-11-25 03:24
Does the following command enable the collectors for you?
```
msiexec /i ".\wmi_exporter-0.9.0-amd64.msi" 'ENABLED_COLLECTORS=os,tcp'
```

**Comment by veeraprathap12** [comment] 2019-11-25 03:35
when we are trying to execute this command it posting error messages
![Capture1](https://user-images.githubusercontent.com/57307102/69510369-5f36ce80-0f02-11ea-93ab-128d55efd97a.PNG)
![Uploading Capture2.PNG…]()

**Comment by breed808** [comment] 2019-11-25 04:16
Try without the `.\` in front. E.G.
```
msiexec /i wmi_exporter-0.9.0-amd64.msi 'ENABLED_COLLECTORS=os,tcp'
```

**Comment by veeraprathap12** [comment] 2019-11-25 04:27
It finally worked!! Thank you so much @breed808 for the quick and valuable response. I would really love to learn from you and help you if you need it anytime. Once again thank you sir for the kind HELP :)

**Comment by breed808** [comment] 2019-11-25 05:15
My pleasure @veeraprathap12. Glad I could help.

**Comment by veeraprathap12** [comment] 2019-11-26 17:55
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled service --telemetry.addr :9182   --collector.service.services-where "Name LIKE 'browser'or Name LIKE 'RemoteRegistry'"
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wmi_exporter
C:\Windows

**Comment by veeraprathap12** [comment] 2019-11-26 19:00
![Cap](https://user-images.githubusercontent.com/57307102/69663755-85688580-104c-11ea-9deb-569e51bb6fb4.PNG)
"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled service --telemetry.addr :9182   --collector.service.services-where "Name LIKE 'browser'or Name LIKE 'wmi_exporter'or Name LIKE 'RemoteRegistry'"

**Comment by carlpett** [comment] 2019-12-27 10:18
Thanks a lot @breed808!

**Closed by carlpett** 2019-12-27 10:18 UTC
