### ISSUE TITLE
import cycle not allowed during build

### ISSUE THREAD

**Issue by nnadig-ebsco** [martinlindhe/wmi_exporter#102] opened 2017-08-04 12:50 UTC
C:\Users\Administrator\go\src\github.com\martinlindhe\wmi_exporter>govendor buil
d +local
import cycle not allowed
package github.com/martinlindhe/wmi_exporter
        imports flag
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
Error: exit status 1

Need help in resolving this.

**Comment by martinlindhe** [comment] 2017-08-04 13:11
That seems odd!
Which go version are you using? (type `go version`) to find out.

By the way, we also provide binaries for all releases here: https://github.com/martinlindhe/wmi_exporter/releases

**Comment by nnadig-ebsco** [comment] 2017-08-04 13:17
I am using 1.8.3
go version go1.8.3 windows/386

I got the project code using go get command that was mentioned.

**Comment by martinlindhe** [comment] 2017-08-04 13:24
I'm also using go 1.8.3. Compiles successfully here.
I'm not sure how to resolve this issue.
If you just need to run the software, please use the provided release files instead.

**Comment by nnadig-ebsco** [comment] 2017-08-04 13:32
Hi,
I need to modify collectors for some customization and build the project, hence I need the source code. Can you share the zip file of the project you are running?
Thanks,
Nrupatunga Nadig
Sr. Site Reliability Engineer
EBSCO Information Services
10 Estes Street
Ipswich, MA 01938
617-653-4221
Email: nnadig@ebsco.com<mailto:tarchibald@ebsco.com>

**Comment by martinlindhe** [comment] 2017-08-04 13:41
>  I need to modify collectors for some customization and build the project, hence I need the source code. Can you share the zip file of the project you are running?

I am using the git repository :-)
Have you had success compiling other golang software with your setup? It seems to be some problems with the installation of golang on your machine, but I am not sure.

**Comment by nnadig-ebsco** [comment] 2017-08-04 14:50
When I take the code from git repo it gives the below error:
C:\Users\Administrator\go\src\github.com\martinlindhe\wmi_exporter>govendor buil
d +local
can't load package: package github.com/martinlindhe/wmi_exporter: no buildable G
o source files in C:\Users\Administrator\go\src\github.com\martinlindhe\wmi_expo
rter
Error: exit status 1

Thanks,
Nrupatunga Nadig
Sr. Site Reliability Engineer
EBSCO Information Services
10 Estes Street
Ipswich, MA 01938
617-653-4221
Email: nnadig@ebsco.com<mailto:tarchibald@ebsco.com>

**Comment by martinlindhe** [comment] 2017-08-04 14:54
I am sorry, I cannot reproduce your issue.

**Comment by martinlindhe** [comment] 2017-08-04 15:25
> When I take the code from git repo it gives the below error: C:\Users\Administrator\go\src\github.com\martinlindhe\wmi_exporter>govendor buil d +local can't load package: package github.com/martinlindhe/wmi_exporter: no buildable G o source files in C:\Users\Administrator\go\src\github.com\martinlindhe\wmi_expo rter Error: exit status 1

This error suggests you are not inside the project root.
When you say you take the code from git repo, did you download a zip file from this website, or used the instructions of the README?

If you followed the readme, there should be a exporter.go (and more files) in the current directory.
If you downloaded a zip, you might have accidentaly created additional sub-directories when extracting it.

I suggest you do a normal git checkout of the repository instead.

**Comment by martinlindhe** [comment] 2017-08-04 15:27
Suggested way of using the git repository:
```
go get -u github.com/kardianos/govendor
go get -u github.com/martinlindhe/wmi_exporter
cd $env:GOPATH/src/github.com/martinlindhe/wmi_exporter
govendor build +local
.\wmi_exporter.exe
```

**Comment by nnadig-ebsco** [comment] 2017-08-04 17:47
I created a new workspace and set the go path to that new workspace and bingo no error..

govendor build +local returned no error but I don’t see wmi_exporter.exe in the current dir.

Where would this be built? And any log file that captures the build?

Thanks,
Nrupatunga Nadig
Sr. Site Reliability Engineer
EBSCO Information Services
10 Estes Street
Ipswich, MA 01938
617-653-4221
Email: nnadig@ebsco.com<mailto:tarchibald@ebsco.com>

**Comment by martinlindhe** [comment] 2017-08-07 10:14
@nnadig-ebsco Assuming you followed the build instructions, you would end up with a wmi_exporter.exe in the same directory you invoked those commands.

I am confident that this issue is not related to the wmi_exporter project, and thus I am closing this.

**Comment by martinlindhe** [comment] 2017-08-09 23:42
@nnadig-ebsco I must apologize for my harsh tone, It was not professional.
I have realized I had forgot to update the build instructions in the README. Indeed, following them along, no .exe was produced.

Please if you have the ability, give this a try, assuming powershell:

    go get -u github.com/kardianos/govendor
    go get -u github.com/prometheus/promu
    go get -u github.com/martinlindhe/wmi_exporter
    cd $env:GOPATH/src/github.com/martinlindhe/wmi_exporter
    promu build -v .
    .\wmi_exporter.exe

**Comment by nnadig-ebsco** [comment] 2017-08-10 14:29
Hi Martin,
No worries. Thanks for the response. After I send an email, I tried it and its creating the exe in by bin dir. I had to issue install command after I build.

I have a question though:
We are trying to generate the metrics depending on custom counters we specify in a config files. For example: instead go iis.go having hard coded counter definitions and code for it, we want to read the counter names from a config/properties file and then generate metrics for that. Do you have any reference or working example for such scenario?

Any inputs appreciated!

Thanks,
Nrupatunga Nadig
Sr. Site Reliability Engineer
EBSCO Information Services
10 Estes Street
Ipswich, MA 01938
617-653-4221
Email: nnadig@ebsco.com<mailto:tarchibald@ebsco.com>

**Comment by martinlindhe** [comment] 2017-08-10 15:47
Glad you got it working!
For custom metrics, there has been some discussin in #87 with some hints, but nothing implemented.
Especially @carlpett raised some concerns in https://github.com/martinlindhe/wmi_exporter/issues/87#issuecomment-312551368.

closing this issue since it is now resolved.

**Closed by martinlindhe** 2017-08-10 15:47 UTC
Labels: question
