### ISSUE TITLE
wmi_logical_disk_size_bytes got wrong data

### ISSUE THREAD

**Issue by demonicksj** [martinlindhe/wmi_exporter#361] opened 2019-07-15 07:18 UTC
There is an issue with gathering the wmi_logical_disk_size_bytes from several windows servers(2008 R2).
Here is the example of issue.

![image](https://user-images.githubusercontent.com/45898183/61200219-aa063580-a71b-11e9-85e0-c07fe23029d2.png)

![image](https://user-images.githubusercontent.com/45898183/61200253-c1ddb980-a71b-11e9-9c55-6643dcc4f8b4.png)

I saw the issue ticket before but we can't modify the soruce on the wmi_exporter.
Please share the way to resolve that issue.

**Comment by avonwyss** [comment] 2019-07-15 07:23
Could be a duplicate of #248

**Comment by demonicksj** [comment] 2019-07-16 05:46
> Could be a duplicate of #248

I saw that issue ticket already but we can't hard cord an wmi_exporter.
Coud you provide updated wmi_exporter msi file for resolving that issue??

Now we are using the latest version of wmi.

**Comment by carlpett** [comment] 2019-07-16 11:18
As mentioned in the linked ticket, we cannot fix this in the exporter. It is a bug in Windows.
The suggested workaround there is to put your correct disk sizes as metrics via for example the textfile collector. It is not a super-clean solution, but it is unfortunately the least bad at the moment.

**Closed by carlpett** 2019-07-16 11:18 UTC
Labels: collector/logical_disk

**Comment by avonwyss** [comment] 2019-07-18 00:31
@demonicksj Try installing the matching Windows hotfix I've linked to in #248. This worked for me at least with Windows 2008 (there is a related/similar hotfix for Windows 2008 R2 available).
