### ISSUE TITLE
Collector error handling

### ISSUE THREAD

**Issue by wizardmatas** [martinlindhe/wmi_exporter#217] opened 2018-06-25 20:35 UTC
Hello, wdyt about not logging errors about failed collector calls like https://github.com/martinlindhe/wmi_exporter/blob/bb67658853cc3cecc3d83e19c466838a54ed6be9/exporter.go#L105 or https://github.com/martinlindhe/wmi_exporter/blob/aecd90dcf127f1c26ade82939cafc1420eed1906/collector/dns.go#L185 on **every** prometheus scrape? it really noises logs. I think it is really useful to log it on exporter service start, but not on every scrape. Usually servers have some roles that are not enabled on all servers ( i.e AD DC, DNS, FileServices and etc) and having different collectors enabled for each server is a bit complicated if you want to do it using GPO installs.

**Comment by carlpett** [comment] 2018-06-26 06:37
Hi,
This is a duplicate of #181. In general, this (configuring which collectors should be enabled) is what we consider a configuration management problem, rather than something that should be solved in the exporter.
This is then further complicated by the fact that it is not all that simple to determine if you get an error because the role is not installed, or because of some other problem (the errors are untyped, use quite vague strings to describe the problem, and those strings are also localized).

I would recommend investigating if you can make your installations only enable the collectors that you actually want enabled.

**Closed by carlpett** 2018-06-26 06:37 UTC
