### ISSUE TITLE
process: invalid query

### ISSUE THREAD

**Issue by bbigras** [martinlindhe/wmi_exporter#115] opened 2017-08-15 23:00 UTC
wmi_exporter-0.2.7
Win 10 64-bit

```
.\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where
" "Name='notepad.exe'"
```

```
2017/08/15 18:57:28 warning: Couldn't open registry to determine IIS version: Le fichier spécifié est introuvable.
time="2017-08-15T18:57:28-04:00" level=info msg="Enabled collectors: process" source="exporter.go:213"
time="2017-08-15T18:57:28-04:00" level=info msg="Starting WMI exporter (version=0.2.7, branch=master, revision=44c39405c
79fd753a710b9b8295df23f7aefa282)" source="exporter.go:224"
time="2017-08-15T18:57:28-04:00" level=info msg="Build context (go=go1.8, user=appvyr-win\\appveyor@APPVYR-WIN, date=201
70810-22:37:09)" source="exporter.go:225"
time="2017-08-15T18:57:28-04:00" level=info msg="Starting server on :9182" source="exporter.go:228"
2017/08/15 18:57:31 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-08-15T18:57:31-04:00" level=error msg="ERROR: process collector failed after 0.016003s: Une exception s’est p
roduite. (Demande non valide )" source="exporter.go:90"
2017/08/15 18:57:31 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-08-15T18:57:31-04:00" level=error msg="ERROR: process collector failed after 0.006001s: Une exception s’est p
roduite. (Demande non valide )" source="exporter.go:90"
```

**Comment by martinlindhe** [comment] 2017-08-16 15:07
I tried the same command on my dev machine, which is also Win10, x64.
For me, it is working correctly. I do not see the errors you are getting.

While I understand this might be frustrating, I am unsure how to assist you further.

Are you certain the given output was actually from the commandline you pasted?

**Comment by bbigras** [comment] 2017-08-17 01:55
I tried in powershell for notepad and firefox. It's weird that I don't have the same error message.
```
PS C:\Program Files\wmi_exporter> .\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "Name='notepad'"
2017/08/16 21:52:19 warning: Couldn't open registry to determine IIS version: Le fichier spécifié est introuvable.
time="2017-08-16T21:52:19-04:00" level=info msg="Enabled collectors: process" source="exporter.go:213"
time="2017-08-16T21:52:19-04:00" level=info msg="Starting WMI exporter (version=0.2.7, branch=master, revision=44c39405c79fd753a710b9b8295df23f7aefa282)" source="exporter.go:224"
time="2017-08-16T21:52:19-04:00" level=info msg="Build context (go=go1.8, user=appvyr-win\\appveyor@APPVYR-WIN, date=20170810-22:37:09)" source="exporter.go:225"
time="2017-08-16T21:52:19-04:00" level=info msg="Starting server on :9182" source="exporter.go:228"
2017/08/16 21:52:22 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Classe non valide )
time="2017-08-16T21:52:22-04:00" level=error msg="ERROR: process collector failed after 0.011002s: Une exception s’est produite. (Classe non valide )" source="exporter.go:90"
2017/08/16 21:52:22 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Classe non valide )
time="2017-08-16T21:52:22-04:00" level=error msg="ERROR: process collector failed after 0.008002s: Une exception s’est produite. (Classe non valide )" source="exporter.go:90"

PS C:\Program Files\wmi_exporter> .\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "Name='firefox'"
2017/08/16 21:53:44 warning: Couldn't open registry to determine IIS version: Le fichier spécifié est introuvable.
time="2017-08-16T21:53:44-04:00" level=info msg="Enabled collectors: process" source="exporter.go:213"
time="2017-08-16T21:53:44-04:00" level=info msg="Starting WMI exporter (version=0.2.7, branch=master, revision=44c39405c79fd753a710b9b8295df23f7aefa282)" source="exporter.go:224"
time="2017-08-16T21:53:44-04:00" level=info msg="Build context (go=go1.8, user=appvyr-win\\appveyor@APPVYR-WIN, date=20170810-22:37:09)" source="exporter.go:225"
time="2017-08-16T21:53:44-04:00" level=info msg="Starting server on :9182" source="exporter.go:228"
2017/08/16 21:53:54 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-08-16T21:53:54-04:00" level=error msg="ERROR: process collector failed after 0.031759s: Une exception s’est produite. (Demande non valide )" source="exporter.go:90"
2017/08/16 21:53:54 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-08-16T21:53:54-04:00" level=error msg="ERROR: process collector failed after 0.008001s: Une exception s’est produite. (Demande non valide )" source="exporter.go:90"
```

Note that my Windows is in french.

**Comment by carlpett** [comment] 2017-09-07 17:56
@bbigras Could you try making the same query outside the exporter?
The equivalent powershell would be `Get-WmiObject -Query "SELECT * FROM Win32_Process WHERE Name = 'notepad'"`

**Comment by bbigras** [comment] 2017-09-07 22:37
`Name = 'notepad'"` doesn't work but `Name = 'notepad.exe'"` does.

```
PS C:\Users\bbigras> Get-WmiObject -Query "SELECT * FROM Win32_Process WHERE Name = 'notepad.exe'"


__GENUS                    : 2
__CLASS                    : Win32_Process
__SUPERCLASS               : CIM_Process
__DYNASTY                  : CIM_ManagedSystemElement
__RELPATH                  : Win32_Process.Handle="16000"
__PROPERTY_COUNT           : 45
__DERIVATION               : {CIM_Process, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                   : DESKTOP-PC3NRS1
__NAMESPACE                : root\cimv2
__PATH                     : \\DESKTOP-PC3NRS1\root\cimv2:Win32_Process.Handle="16000"
Caption                    : notepad.exe
CommandLine                : "C:\WINDOWS\system32\notepad.exe"
CreationClassName          : Win32_Process
CreationDate               : 20170907183548.754221-240
CSCreationClassName        : Win32_ComputerSystem
CSName                     : DESKTOP-PC3NRS1
Description                : notepad.exe
ExecutablePath             : C:\WINDOWS\system32\notepad.exe
ExecutionState             :
Handle                     : 16000
HandleCount                : 219
InstallDate                :
KernelModeTime             : 468750
MaximumWorkingSetSize      : 1380
MinimumWorkingSetSize      : 200
Name                       : notepad.exe
OSCreationClassName        : Win32_OperatingSystem
OSName                     : Microsoft Windows 10 Famille|C:\WINDOWS|\Device\Harddisk1\Partition1
OtherOperationCount        : 145
OtherTransferCount         : 142
PageFaults                 : 3506
PageFileUsage              : 2984
ParentProcessId            : 14036
PeakPageFileUsage          : 2992
PeakVirtualSize            : 2199169687552
PeakWorkingSetSize         : 13356
Priority                   : 8
PrivatePageCount           : 3055616
ProcessId                  : 16000
QuotaNonPagedPoolUsage     : 14
QuotaPagedPoolUsage        : 238
QuotaPeakNonPagedPoolUsage : 14
QuotaPeakPagedPoolUsage    : 255
ReadOperationCount         : 2
ReadTransferCount          : 8350
SessionId                  : 18
Status                     :
TerminationDate            :
ThreadCount                : 7
UserModeTime               : 0
VirtualSize                : 2199161389056
WindowsVersion             : 10.0.15063
WorkingSetSize             : 13676544
WriteOperationCount        : 0
WriteTransferCount         : 0
PSComputerName             : DESKTOP-PC3NRS1
ProcessName                : notepad.exe
Handles                    : 219
VM                         : 2199161389056
WS                         : 13676544
Path                       : C:\WINDOWS\system32\notepad.exe
```

**Comment by martinlindhe** [comment] 2017-09-07 23:47
Hm, this has me confused.
I do recall we tested this working without the .exe extension..
However, I now get the same result as @bbigras when doing the raw query. Win10 x64, English version

Could you help verify @carlpett, maybe we need to correct the examples in the doc?

**Comment by carlpett** [comment] 2017-09-08 08:42
@bbigras Really weird. Could you try adding a log statement which outputs the query to collector/process.go? 
Basically add `log.Println(q)` here: 
https://github.com/martinlindhe/wmi_exporter/blob/94caf8ee61027bd02ae694353597741182b00829/collector/process.go#L183-L187

@martinlindhe You only get one firefox process due to matching exactly on `'firefox'`. WMI separates multiple instances of the same name by adding a number after the name, so you get `firefox.exe`, `firefox.exe#1` and `firefox.exe#2`. These suffixes are handled here, if present: https://github.com/martinlindhe/wmi_exporter/blob/94caf8ee61027bd02ae694353597741182b00829/collector/process.go#L194-L195

To get all the processes, you need to change the where-clause to `Name LIKE 'firefox%'`, though. I thought this was documented somewhere, but I don't see it now...

**Comment by martinlindhe** [comment] 2017-09-08 09:30
@carlpett Okay, that's good!

I am still confused as of what black magic makes wmi_exporter match on Name="firefox" (without .exe), but the same won't work as a raw query.

Finally, the error @bbigras is getting from doing this, I think it must be about some extra characters sneaking their way into his command. Like a newline or a space that shouldn't be there.

**Comment by carlpett** [comment] 2017-09-08 09:33
Hm, we actually use a different class, probably that is why. `Win32_PerfRawData_PerfProc_Process`, not `Win32_Process`. I misremembered, sorry.

Yeah, either some extra characters, or possibly there might be some localization issue? `'` or `"` might not be the ascii variants?

**Comment by martinlindhe** [comment] 2017-09-08 09:53
Ah, mystery solved! I confirmed Win32_PerfRawData_PerfProc_Process.Name does not have .exe

Right, the quote characters might also be to blame.

So @bbigras since you got the `Get-WmiObject -Query "SELECT * FROM Win32_Process WHERE Name = 'notepad.exe'"`
command running on the command-line, could you 

1) verify that this also works (it should):
```
Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_PerfProc_Process WHERE Name = 'notepad'"
```

and then
2)

try (copy and paste) this:
```
.\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where" "Name='notepad'"
```

if command 1 works but not 2, we suspect it is due to how the command was typed, as there are multiple characters that looks like `'` and `"`, and they can be basically identical in some fonts.

**Comment by bbigras** [comment] 2017-09-08 21:33
command 1 didn't work:
```
PS C:\Users\bbigras> Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_PerfProc_Process WHERE Name = 'notepad'"
Get-WmiObject : Classe non valide « Win32_PerfRawData_PerfProc_Process »
Au caractère Ligne:1 : 1
+ Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_PerfProc_Proces ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

**Comment by bbigras** [comment] 2017-09-08 23:48
I don't have "Disable Performance Counters" in 
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfProc\Performance`.

**Comment by martinlindhe** [comment] 2017-09-08 23:49
Okay, more general quote from other source:

> Apparently performance counters can be disabled via the Windows registry. Should this happen after a Windows Update or the installation of some software package, search in the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services branch for "Disable Performance Counters". If you find one or more entries set to "1", set them to "0".

> One case where this has helped is the WMI Process sensor, where setting this key in the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfProc\Performance branch brought red sensors back online.

**Comment by martinlindhe** [comment] 2017-09-08 23:51
(Notes from https://kb.paessler.com/en/topic/3713-i-have-tried-a-lot-of-things-to-fix-my-wmi-what-else-can-i-try-to-avoid-reinstalling-windows, there is more suggestions for troubleshooting WMI there, especially about missing performance counters)

**Comment by bbigras** [comment] 2017-09-09 00:08
I ran:
```
sfc /scannow
wmiadap /f
wmiadap /r
```

and now `Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_PerfProc_Process WHERE Name = 'notepad'"` works.

but command 2 doesn't:

```
PS C:\Program Files\wmi_exporter> .\wmi_exporter.exe "-collectors.enabled" "process" "-collector.process.processes-where
" "Name='notepad'"
2017/09/08 20:06:16 warning: Couldn't open registry to determine IIS version: Le fichier spécifié est introuvable.
time="2017-09-08T20:06:16-04:00" level=info msg="Enabled collectors: process" source="exporter.go:213"
time="2017-09-08T20:06:16-04:00" level=info msg="Starting WMI exporter (version=0.2.7, branch=master, revision=44c39405c
79fd753a710b9b8295df23f7aefa282)" source="exporter.go:224"
time="2017-09-08T20:06:16-04:00" level=info msg="Build context (go=go1.8, user=appvyr-win\\appveyor@APPVYR-WIN, date=201
70810-22:37:09)" source="exporter.go:225"
time="2017-09-08T20:06:16-04:00" level=info msg="Starting server on :9182" source="exporter.go:228"
2017/09/08 20:06:23 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-09-08T20:06:23-04:00" level=error msg="ERROR: process collector failed after 0.016003s: Une exception s’est p
roduite. (Demande non valide )" source="exporter.go:90"
2017/09/08 20:06:23 [ERROR] failed collecting process metrics: <nil> Une exception s’est produite. (Demande non valide )
time="2017-09-08T20:06:23-04:00" level=error msg="ERROR: process collector failed after 0.007000s: Une exception s’est p
roduite. (Demande non valide )" source="exporter.go:90"
```

**Comment by martinlindhe** [comment] 2017-09-09 00:25
Okay, that's progress.

While reviewing your earlier comments, I notice that in the initial comment https://github.com/martinlindhe/wmi_exporter/issues/115#issue-250462661 you got the error `Demande non valide`,

while in https://github.com/martinlindhe/wmi_exporter/issues/115#issuecomment-322947330 you got `Classe non valide` (the WMI class was not available),

Now again in https://github.com/martinlindhe/wmi_exporter/issues/115#issuecomment-328240299 you are getting `Demande non valide`.

I'm sorry to say these are issues with the WMI component in Windows, I don't exactly know how to resolve them.

**Comment by martinlindhe** [comment] 2017-11-18 15:08
@bbigras did you resolve this?

**Comment by carlpett** [comment] 2018-02-14 14:28
We've seen the "invalid query" in another bug, where there were fields that were not exposed from Windows for some reason. 
Let's close this for now, since it doesn't seem to be an issue any more, but the above would be interesting to investigate next time.

**Closed by carlpett** 2018-02-14 14:28 UTC
