### ISSUE TITLE
Feature Request: Add textfile collector

### ISSUE THREAD

**Issue by cukal** [martinlindhe/wmi_exporter#158] opened 2018-02-12 17:47 UTC
Hi, 

Thanks for an already excellent wmi exporter for Prometheus! 
I needed the textfile collector today for a windows host and a batch job but noticed it wasn't available. 
Any plans to add it to wmi_exporter?

**Comment by brian-brazil** [comment] 2018-02-12 18:19
This is a duplicate of #33

**Closed by brian-brazil** 2018-02-12 18:19 UTC
