### ISSUE TITLE
Feature Request: Monitoring for Hyper-V via WMI

### ISSUE THREAD

**Issue by Keleir** [martinlindhe/wmi_exporter#103] opened 2017-08-07 04:02 UTC
I have do a research about [**Hyper-V WMI API**](https://msdn.microsoft.com/library/hh850319.aspx) and [**Win32_PerfRawData**](http://wutils.com/wmi/root/cimv2/win32_perfrawdata/#Childs), 
there also contains amount of performance data about Hyper-V, such as  `Win32_PerfFormattedData_HvStats_HyperVHypervisorVirtualProcessor`, 
`Win32_PerfFormattedData_Counters_HyperVVirtualStorageDevice`,
`Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor`, etc. 
Does it can included into wmi_exporter's collector moudle  with a `hyperv.go`? 
There is a need for me to monitor Hypervisor virtual machines. Thanks a lot !

Best Regards,
Kallen Ding

**Comment by carlpett** [comment] 2017-08-07 07:52
Hi,
This is a duplicate of #101.

**Closed by carlpett** 2017-08-07 07:52 UTC
